/**
 * Design Tokens — Sizes (Spacing, Border Radius)
 * Auto-generated from Figma Variables API.
 * DO NOT EDIT — run: npm run update-tokens
 *
 * Generated: 2026-04-01T16:02:45.010Z
 */

module.exports = {
  spacing: {
    'spacing-0': '0px' /* Spacing/spacing-0 */,
    'spacing-2': '2px' /* Spacing/spacing-2 */,
    'spacing-4': '4px' /* Spacing/spacing-4 */,
    'spacing-6': '6px' /* Spacing/spacing-6 */,
    'spacing-8': '8px' /* Spacing/spacing-8 */,
    'spacing-10': '10px' /* Spacing/spacing-10 */,
    'spacing-12': '12px' /* Spacing/spacing-12 */,
    'spacing-14': '14px' /* Spacing/spacing-14 */,
    'spacing-16': '16px' /* Spacing/spacing-16 */,
    'spacing-20': '20px' /* Spacing/spacing-20 */,
    'spacing-24': '24px' /* Spacing/spacing-24 */,
    'spacing-28': '28px' /* Spacing/spacing-28 */,
    'spacing-32': '32px' /* Spacing/spacing-32 */,
    'spacing-36': '36px' /* Spacing/spacing-36 */,
    'spacing-40': '40px' /* Spacing/spacing-40 */,
    'spacing-48': '48px' /* Spacing/spacing-48 */,
    'spacing-52': '52px' /* Spacing/spacing-52 */,
    'spacing-56': '56px' /* Spacing/spacing-56 */,
    'spacing-64': '64px' /* Spacing/spacing-64 */,
    'spacing-72': '72px' /* Spacing/spacing-72 */,
    'spacing-80': '80px' /* Spacing/spacing-80 */,
    'border-4xs': '1px' /* Border/border-4XS */,
    'border-3xs': '1px' /* Border/border-3XS */,
    'border-2xs': '2px' /* Border/border-2XS */,
    'border-xs': '4px' /* Border/border-XS */,
    'border-s': '6px' /* Border/border-S */,
    'border-m': '8px' /* Border/border-M */,
    'border-l': '12px' /* Border/border-L */,
    'border-xl': '16px' /* Border/border-XL */,
    'border-2xl': '24px' /* Border/border-2XL */,
    'border-3xl': '32px' /* Border/border-3XL */,
    'border-4xl': '40px' /* Border/border-4XL */,
    'base-0': '0px' /* Base/base-0 */,
    'base-0,8': '1px' /* Base/base-0,8 */,
    'base-1': '1px' /* Base/base-1 */,
    'base-2': '2px' /* Base/base-2 */,
    'base-4': '4px' /* Base/base-4 */,
    'base-6': '6px' /* Base/base-6 */,
    'base-8': '8px' /* Base/base-8 */,
    'base-10': '10px' /* Base/base-10 */,
    'base-12': '12px' /* Base/base-12 */,
    'base-14': '14px' /* Base/base-14 */,
    'base-16': '16px' /* Base/base-16 */,
    'base-18': '18px' /* Base/base-18 */,
    'base-20': '20px' /* Base/base-20 */,
    'base-24': '24px' /* Base/base-24 */,
    'base-28': '28px' /* Base/base-28 */,
    'base-32': '32px' /* Base/base-32 */,
    'base-36': '36px' /* Base/base-36 */,
    'base-40': '40px' /* Base/base-40 */,
    'base-48': '48px' /* Base/base-48 */,
    'base-52': '52px' /* Base/base-52 */,
    'base-56': '56px' /* Base/base-56 */,
    'base-60': '60px' /* Base/base-60 */,
    'base-64': '64px' /* Base/base-64 */,
    'base-72': '72px' /* Base/base-72 */,
    'base-80': '80px' /* Base/base-80 */,
  },
  borderRadius: {
    'radius-0': '0px' /* Radius/radius-0 */,
    'radius-1': '1px' /* Radius/radius-1 */,
    'radius-2': '2px' /* Radius/radius-2 */,
    'radius-4': '4px' /* Radius/radius-4 */,
    'radius-6': '6px' /* Radius/radius-6 */,
    'radius-8': '8px' /* Radius/radius-8 */,
    'radius-12': '12px' /* Radius/radius-12 */,
    'radius-16': '16px' /* Radius/radius-16 */,
    'radius-20': '20px' /* Radius/radius-20 */,
    'radius-24': '24px' /* Radius/radius-24 */,
    'radius-32': '32px' /* Radius/radius-32 */,
    'radius-40': '40px' /* Radius/radius-40 */,
    'radius-80': '80px' /* Radius/radius-80 */,
  },
  opacity: {
    statedefault: '1' /* Opacity/stateDefault */,
    statehovered: '0.8' /* Opacity/stateHovered */,
    statefocused: '0.7' /* Opacity/stateFocused */,
    statedisabled: '0.35' /* Opacity/stateDisabled */,
  },
};
