/**
 * Tailwind Theme Tokens — Pre-generated CSS variable references
 * Auto-generated from Figma Variables API.
 * DO NOT EDIT — run: npm run update-tokens
 *
 * Generated: 2026-04-01T16:02:45.011Z
 */

module.exports = {
  colors: {
    brand: {
      text___icon: 'var(--brand-text___icon)',
      base: 'var(--brand-base)',
      bg: 'var(--brand-bg)',
      bg_deep: 'var(--brand-bg_deep)',
      faded: 'var(--brand-faded)',
    },
    texticon: {
      black_inverse_a100: 'var(--texticon-black_inverse_a100)',
      black_inverse_a56: 'var(--texticon-black_inverse_a56)',
      black_inverse_a32: 'var(--texticon-black_inverse_a32)',
      black_inverse_a0: 'var(--texticon-black_inverse_a0)',
      white_inverse_a100: 'var(--texticon-white_inverse_a100)',
      white_inverse_a60: 'var(--texticon-white_inverse_a60)',
      fixed_black: 'var(--texticon-fixed_black)',
      fixed_white: 'var(--texticon-fixed_white)',
      white_inverse_a40: 'var(--texticon-white_inverse_a40)',
      white_inverse_a0: 'var(--texticon-white_inverse_a0)',
    },
    stroke: {
      a72: 'var(--stroke-a72)',
      a12: 'var(--stroke-a12)',
      a8: 'var(--stroke-a8)',
      a6: 'var(--stroke-a6)',
      a4: 'var(--stroke-a4)',
    },
    wrapper: {
      a100: 'var(--wrapper-a100)',
      a88: 'var(--wrapper-a88)',
      a12: 'var(--wrapper-a12)',
      a8: 'var(--wrapper-a8)',
      a6: 'var(--wrapper-a6)',
      a4: 'var(--wrapper-a4)',
      a2: 'var(--wrapper-a2)',
      a0: 'var(--wrapper-a0)',
    },
    background: {
      white_high: 'var(--background-white_high)',
      white_medium: 'var(--background-white_medium)',
      white_low: 'var(--background-white_low)',
      gray_high: 'var(--background-gray_high)',
      gray_medium: 'var(--background-gray_medium)',
      gray_low: 'var(--background-gray_low)',
      gray_faded: 'var(--background-gray_faded)',
      bg_bgweb: 'var(--background-bg_bgweb)',
      bg_bgapp: 'var(--background-bg_bgapp)',
      bgbase________: 'var(--background-bgbase________)',
      bgthin________: 'var(--background-bgthin________)',
      bgregular________: 'var(--background-bgregular________)',
      bgmedium________: 'var(--background-bgmedium________)',
      bgweb: 'var(--background-bgweb)',
      bgapp: 'var(--background-bgapp)',
    },
    overlay: {
      base: 'var(--overlay-base)',
      medium: 'var(--overlay-medium)',
      bold: 'var(--overlay-bold)',
      light: 'var(--overlay-light)',
    },
    colors: {
      status_success_base: 'var(--colors-status_success_base)',
      status_success_bg: 'var(--colors-status_success_bg)',
      status_warning_base: 'var(--colors-status_warning_base)',
      status_warning_bg: 'var(--colors-status_warning_bg)',
      status_negative_base: 'var(--colors-status_negative_base)',
      status_negative_bg: 'var(--colors-status_negative_bg)',
      status_success_faded: 'var(--colors-status_success_faded)',
      status_warning_faded: 'var(--colors-status_warning_faded)',
      status_negative_faded: 'var(--colors-status_negative_faded)',
      other_brown: 'var(--colors-other_brown)',
      other_yellow: 'var(--colors-other_yellow)',
      other_pink: 'var(--colors-other_pink)',
      other_purple: 'var(--colors-other_purple)',
      other_blue: 'var(--colors-other_blue)',
      other_cyan: 'var(--colors-other_cyan)',
      other_lime: 'var(--colors-other_lime)',
    },
    whiteinverse: {
      a90: 'var(--whiteinverse-a90)',
      a80: 'var(--whiteinverse-a80)',
      a20: 'var(--whiteinverse-a20)',
      a12: 'var(--whiteinverse-a12)',
      a8: 'var(--whiteinverse-a8)',
      a6: 'var(--whiteinverse-a6)',
      a4: 'var(--whiteinverse-a4)',
      a100: 'var(--whiteinverse-a100)',
      a60: 'var(--whiteinverse-a60)',
      a40: 'var(--whiteinverse-a40)',
      a0: 'var(--whiteinverse-a0)',
    },
    surfacelow: {
      surfacelow1: 'var(--surfacelow-surfacelow1)',
      surfacelow2a: 'var(--surfacelow-surfacelow2a)',
      surfacelow3: 'var(--surfacelow-surfacelow3)',
      surfacelow3a: 'var(--surfacelow-surfacelow3a)',
      surfacelow4: 'var(--surfacelow-surfacelow4)',
      surfacelow4a: 'var(--surfacelow-surfacelow4a)',
      surfacelow5: 'var(--surfacelow-surfacelow5)',
    },
    surfacemedium: {
      surfacemedium: 'var(--surfacemedium-surfacemedium)',
      surfacemedium2: 'var(--surfacemedium-surfacemedium2)',
      surfacemedium2a: 'var(--surfacemedium-surfacemedium2a)',
      surfacemedium3: 'var(--surfacemedium-surfacemedium3)',
      surfacemedium3a: 'var(--surfacemedium-surfacemedium3a)',
      surfacemedium4: 'var(--surfacemedium-surfacemedium4)',
      surfacemedium4a: 'var(--surfacemedium-surfacemedium4a)',
      surfacemedium5: 'var(--surfacemedium-surfacemedium5)',
    },
    base: {
      black_blackbase: 'var(--base-black_blackbase)',
      black_blackbasea72: 'var(--base-black_blackbasea72)',
      black_blackbasea56: 'var(--base-black_blackbasea56)',
      black_blackbasea32: 'var(--base-black_blackbasea32)',
      black_blackbasea12: 'var(--base-black_blackbasea12)',
      black_blackbasea8: 'var(--base-black_blackbasea8)',
      black_blackbasea6: 'var(--base-black_blackbasea6)',
      black_blackbasea4: 'var(--base-black_blackbasea4)',
      gray_graybaseultrathin: 'var(--base-gray_graybaseultrathin)',
      gray_graybaseultrathina60: 'var(--base-gray_graybaseultrathina60)',
      gray_graybasethin: 'var(--base-gray_graybasethin)',
      gray_graybasethina60: 'var(--base-gray_graybasethina60)',
      gray_graybaseregular: 'var(--base-gray_graybaseregular)',
      gray_graybaseregulara60: 'var(--base-gray_graybaseregulara60)',
      gray_graybasemedium: 'var(--base-gray_graybasemedium)',
      gray_graybasemediuma60: 'var(--base-gray_graybasemediuma60)',
      gray_graybasestrong: 'var(--base-gray_graybasestrong)',
      gray_graybasebold: 'var(--base-gray_graybasebold)',
      white_whitebase: 'var(--base-white_whitebase)',
      white_whitebasea80: 'var(--base-white_whitebasea80)',
      white_whitebasea60: 'var(--base-white_whitebasea60)',
      white_whitebasea40: 'var(--base-white_whitebasea40)',
      white_whitebasea20: 'var(--base-white_whitebasea20)',
      white_whitebasea12: 'var(--base-white_whitebasea12)',
      white_whitebasea8: 'var(--base-white_whitebasea8)',
      white_whitebasea6: 'var(--base-white_whitebasea6)',
      white_whitebasea0: 'var(--base-white_whitebasea0)',
      accent_accentprimary: 'var(--base-accent_accentprimary)',
      accent_accentprimarya60: 'var(--base-accent_accentprimarya60)',
      accent_accentprimarya40: 'var(--base-accent_accentprimarya40)',
      accent_accentprimarya20: 'var(--base-accent_accentprimarya20)',
      accent_accentprimarya8: 'var(--base-accent_accentprimarya8)',
      accent_accentprimarya0: 'var(--base-accent_accentprimarya0)',
      accent_accentdanger: 'var(--base-accent_accentdanger)',
      accent_accentdangera60: 'var(--base-accent_accentdangera60)',
      accent_accentdangera40: 'var(--base-accent_accentdangera40)',
      accent_accentdangera20: 'var(--base-accent_accentdangera20)',
      accent_accentdangera8: 'var(--base-accent_accentdangera8)',
      accent_accentdangera0: 'var(--base-accent_accentdangera0)',
      accent_accentsuccess: 'var(--base-accent_accentsuccess)',
      accent_accentsuccessa60: 'var(--base-accent_accentsuccessa60)',
      accent_accentsuccessa40: 'var(--base-accent_accentsuccessa40)',
      accent_accentsuccessa20: 'var(--base-accent_accentsuccessa20)',
      accent_accentsuccessa8: 'var(--base-accent_accentsuccessa8)',
      accent_accentsuccessa0: 'var(--base-accent_accentsuccessa0)',
      accent_accentwarning: 'var(--base-accent_accentwarning)',
      accent_accentwarninga60: 'var(--base-accent_accentwarninga60)',
      accent_accentwarninga40: 'var(--base-accent_accentwarninga40)',
      accent_accentwarninga20: 'var(--base-accent_accentwarninga20)',
      accent_accentwarninga8: 'var(--base-accent_accentwarninga8)',
      accent_accentwarninga0: 'var(--base-accent_accentwarninga0)',
      rgb___________terracottasunset:
        'var(--base-rgb___________terracottasunset)',
      rgb___________terracottasunseta12:
        'var(--base-rgb___________terracottasunseta12)',
      rgb___________terracottasunseta0:
        'var(--base-rgb___________terracottasunseta0)',
      rgb___________coralcalm: 'var(--base-rgb___________coralcalm)',
      rgb___________coralcalma12: 'var(--base-rgb___________coralcalma12)',
      rgb___________coralcalma0: 'var(--base-rgb___________coralcalma0)',
      rgb___________winewood: 'var(--base-rgb___________winewood)',
      rgb___________winewooda12: 'var(--base-rgb___________winewooda12)',
      rgb___________winewooda0: 'var(--base-rgb___________winewooda0)',
      rgb___________lavenderdusk: 'var(--base-rgb___________lavenderdusk)',
      rgb___________lavenderduska12:
        'var(--base-rgb___________lavenderduska12)',
      rgb___________lavenderduska0: 'var(--base-rgb___________lavenderduska0)',
      rgb___________icylagoon: 'var(--base-rgb___________icylagoon)',
      rgb___________icylagoona12: 'var(--base-rgb___________icylagoona12)',
      rgb___________icylagoona0: 'var(--base-rgb___________icylagoona0)',
      rgb___________northernsea: 'var(--base-rgb___________northernsea)',
      rgb___________northernseaa12: 'var(--base-rgb___________northernseaa12)',
      rgb___________northernseaa0: 'var(--base-rgb___________northernseaa0)',
      rgb___________forest: 'var(--base-rgb___________forest)',
      rgb___________foresta12: 'var(--base-rgb___________foresta12)',
      rgb___________foresta0: 'var(--base-rgb___________foresta0)',
      rgb___________lime: 'var(--base-rgb___________lime)',
      rgb___________limea12: 'var(--base-rgb___________limea12)',
      rgb___________limea0: 'var(--base-rgb___________limea0)',
      rgb___________warmsandstone: 'var(--base-rgb___________warmsandstone)',
      rgb___________warmsandstonea12:
        'var(--base-rgb___________warmsandstonea12)',
      rgb___________warmsandstonea0:
        'var(--base-rgb___________warmsandstonea0)',
      rgb____________limea0: 'var(--base-rgb____________limea0)',
    },
    mind: {
      brand: 'var(--mind-brand)',
      accent: 'var(--mind-accent)',
    },
    status: {
      success: 'var(--status-success)',
      warning: 'var(--status-warning)',
      negative: 'var(--status-negative)',
    },
    other: {
      brown: 'var(--other-brown)',
      yellow: 'var(--other-yellow)',
      pink: 'var(--other-pink)',
      purple: 'var(--other-purple)',
      cyan: 'var(--other-cyan)',
    },
    blackinverse: {
      a100: 'var(--blackinverse-a100)',
      a88: 'var(--blackinverse-a88)',
      a72: 'var(--blackinverse-a72)',
      a56: 'var(--blackinverse-a56)',
      a32: 'var(--blackinverse-a32)',
      a12: 'var(--blackinverse-a12)',
      a8: 'var(--blackinverse-a8)',
      a6: 'var(--blackinverse-a6)',
      a4: 'var(--blackinverse-a4)',
      a2: 'var(--blackinverse-a2)',
      a0: 'var(--blackinverse-a0)',
    },
    surfacewhite: {
      low: 'var(--surfacewhite-low)',
      medium: 'var(--surfacewhite-medium)',
      high: 'var(--surfacewhite-high)',
    },
    surfacegray: {
      faded: 'var(--surfacegray-faded)',
      medium: 'var(--surfacegray-medium)',
      high: 'var(--surfacegray-high)',
    },
  },
  spacing: {
    separator_size_: '1px',
    borderxxxs: '1px',
    borderxxs: '2px',
    s2: '2px',
    contentmax_l: '440px',
  },
  borderRadius: {},
  boxShadow: {
    100: 'var(--shadow-100)',
    200: 'var(--shadow-200)',
    300: 'var(--shadow-300)',
    400: 'var(--shadow-400)',
    500: 'var(--shadow-500)',
    600: 'var(--shadow-600)',
    'effects-modal': 'var(--shadow-effects-modal)',
    'effects-panel': 'var(--shadow-effects-panel)',
  },
  backdropBlur: {
    medium: 'var(--blur-medium)',
    high: 'var(--blur-high)',
    extra: 'var(--blur-extra)',
    normal: 'var(--blur-normal)',
    ultra: 'var(--blur-ultra)',
    low: 'var(--blur-low)',
    'effects-modal': 'var(--blur-effects-modal)',
    'effects-panel': 'var(--blur-effects-panel)',
    'progressiveblur-bottom-normal':
      'var(--blur-progressiveblur-bottom-normal)',
    'progressiveblur-bottom-medium':
      'var(--blur-progressiveblur-bottom-medium)',
    'progressiveblur-top-medium': 'var(--blur-progressiveblur-top-medium)',
    'progressiveblur-top-normal': 'var(--blur-progressiveblur-top-normal)',
  },
  blur: {
    medium: 'var(--blur-medium)',
    high: 'var(--blur-high)',
    extra: 'var(--blur-extra)',
    normal: 'var(--blur-normal)',
    ultra: 'var(--blur-ultra)',
    low: 'var(--blur-low)',
    'effects-modal': 'var(--blur-effects-modal)',
    'effects-panel': 'var(--blur-effects-panel)',
    'progressiveblur-bottom-normal':
      'var(--blur-progressiveblur-bottom-normal)',
    'progressiveblur-bottom-medium':
      'var(--blur-progressiveblur-bottom-medium)',
    'progressiveblur-top-medium': 'var(--blur-progressiveblur-top-medium)',
    'progressiveblur-top-normal': 'var(--blur-progressiveblur-top-normal)',
  },
};
