import { FC, SVGProps } from 'react';

import { IconCountryFlagVariant } from './IconCountryFlag.types';

type SvgComponent = FC<SVGProps<SVGSVGElement>>;
type SvgLoader = () => Promise<{ default: SvgComponent }>;

// Dynamic import loaders — each flag is loaded only when first used
export const flagLoaders: Record<IconCountryFlagVariant, SvgLoader> = {
  abkhazia: () => import('./flags/abkhazia.svg'),
  afghanistan: () => import('./flags/afghanistan.svg'),
  alandIslands: () => import('./flags/alandIslands.svg'),
  albania: () => import('./flags/albania.svg'),
  algeria: () => import('./flags/algeria.svg'),
  americanSamoa: () => import('./flags/americanSamoa.svg'),
  andorra: () => import('./flags/andorra.svg'),
  angola: () => import('./flags/angola.svg'),
  anguilla: () => import('./flags/anguilla.svg'),
  antiguaAndBarbuda: () => import('./flags/antiguaAndBarbuda.svg'),
  argentina: () => import('./flags/argentina.svg'),
  armenia: () => import('./flags/armenia.svg'),
  aruba: () => import('./flags/aruba.svg'),
  australia: () => import('./flags/australia.svg'),
  austria: () => import('./flags/austria.svg'),
  azerbaijan: () => import('./flags/azerbaijan.svg'),
  azoresIslands: () => import('./flags/azoresIslands.svg'),
  bahamas: () => import('./flags/bahamas.svg'),
  bahrain: () => import('./flags/bahrain.svg'),
  balearicIslands: () => import('./flags/balearicIslands.svg'),
  bangladesh: () => import('./flags/bangladesh.svg'),
  barbados: () => import('./flags/barbados.svg'),
  basqueCountry: () => import('./flags/basqueCountry.svg'),
  belarus: () => import('./flags/belarus.svg'),
  belgium: () => import('./flags/belgium.svg'),
  belize: () => import('./flags/belize.svg'),
  benin: () => import('./flags/benin.svg'),
  bermuda: () => import('./flags/bermuda.svg'),
  bhutan: () => import('./flags/bhutan.svg'),
  bhutan1: () => import('./flags/bhutan1.svg'),
  bolivia: () => import('./flags/bolivia.svg'),
  bonaire: () => import('./flags/bonaire.svg'),
  bosniaAndHerzegovina: () => import('./flags/bosniaAndHerzegovina.svg'),
  botswana: () => import('./flags/botswana.svg'),
  brazil: () => import('./flags/brazil.svg'),
  britishColumbia: () => import('./flags/britishColumbia.svg'),
  britishIndianOceanTerritory: () =>
    import('./flags/britishIndianOceanTerritory.svg'),
  britishVirginIslands: () => import('./flags/britishVirginIslands.svg'),
  brunei: () => import('./flags/brunei.svg'),
  bulgaria: () => import('./flags/bulgaria.svg'),
  burkinaFaso: () => import('./flags/burkinaFaso.svg'),
  burundi: () => import('./flags/burundi.svg'),
  cambodia: () => import('./flags/cambodia.svg'),
  cameroon: () => import('./flags/cameroon.svg'),
  canada: () => import('./flags/canada.svg'),
  canaryIslands: () => import('./flags/canaryIslands.svg'),
  capeVerde: () => import('./flags/capeVerde.svg'),
  caymanIslands: () => import('./flags/caymanIslands.svg'),
  centralAfricanRepublic: () => import('./flags/centralAfricanRepublic.svg'),
  ceuta: () => import('./flags/ceuta.svg'),
  chad: () => import('./flags/chad.svg'),
  chile: () => import('./flags/chile.svg'),
  china: () => import('./flags/china.svg'),
  christmasIsland: () => import('./flags/christmasIsland.svg'),
  cocosIsland: () => import('./flags/cocosIsland.svg'),
  colombia: () => import('./flags/colombia.svg'),
  comoros: () => import('./flags/comoros.svg'),
  cookIslands: () => import('./flags/cookIslands.svg'),
  corsica: () => import('./flags/corsica.svg'),
  costaRica: () => import('./flags/costaRica.svg'),
  croatia: () => import('./flags/croatia.svg'),
  cuba: () => import('./flags/cuba.svg'),
  curacao: () => import('./flags/curacao.svg'),
  cyprus: () => import('./flags/cyprus.svg'),
  czechRepublic: () => import('./flags/czechRepublic.svg'),
  democraticRepublicOfCongo: () =>
    import('./flags/democraticRepublicOfCongo.svg'),
  denmark: () => import('./flags/denmark.svg'),
  djibouti: () => import('./flags/djibouti.svg'),
  dominica: () => import('./flags/dominica.svg'),
  dominicanRepublic: () => import('./flags/dominicanRepublic.svg'),
  eastTimor: () => import('./flags/eastTimor.svg'),
  ecuador: () => import('./flags/ecuador.svg'),
  egypt: () => import('./flags/egypt.svg'),
  england: () => import('./flags/england.svg'),
  equatorialGuinea: () => import('./flags/equatorialGuinea.svg'),
  eritrea: () => import('./flags/eritrea.svg'),
  estonia: () => import('./flags/estonia.svg'),
  ethiopia: () => import('./flags/ethiopia.svg'),
  europeanUnion: () => import('./flags/europeanUnion.svg'),
  falklandIslands: () => import('./flags/falklandIslands.svg'),
  faroeIslands: () => import('./flags/faroeIslands.svg'),
  fiji: () => import('./flags/fiji.svg'),
  finland: () => import('./flags/finland.svg'),
  france: () => import('./flags/france.svg'),
  frenchPolynesia: () => import('./flags/frenchPolynesia.svg'),
  gabon: () => import('./flags/gabon.svg'),
  galapagosIslands: () => import('./flags/galapagosIslands.svg'),
  gambia: () => import('./flags/gambia.svg'),
  georgia: () => import('./flags/georgia.svg'),
  germany: () => import('./flags/germany.svg'),
  ghana: () => import('./flags/ghana.svg'),
  gibraltar: () => import('./flags/gibraltar.svg'),
  greece: () => import('./flags/greece.svg'),
  greenland: () => import('./flags/greenland.svg'),
  grenada: () => import('./flags/grenada.svg'),
  guam: () => import('./flags/guam.svg'),
  guatemala: () => import('./flags/guatemala.svg'),
  guernsey: () => import('./flags/guernsey.svg'),
  guinea: () => import('./flags/guinea.svg'),
  guineaBissau: () => import('./flags/guineaBissau.svg'),
  guyana: () => import('./flags/guyana.svg'),
  haiti: () => import('./flags/haiti.svg'),
  hawaii: () => import('./flags/hawaii.svg'),
  honduras: () => import('./flags/honduras.svg'),
  hongKong: () => import('./flags/hongKong.svg'),
  hungary: () => import('./flags/hungary.svg'),
  iceland: () => import('./flags/iceland.svg'),
  india: () => import('./flags/india.svg'),
  indonesia: () => import('./flags/indonesia.svg'),
  iran: () => import('./flags/iran.svg'),
  iraq: () => import('./flags/iraq.svg'),
  ireland: () => import('./flags/ireland.svg'),
  isleOfMan: () => import('./flags/isleOfMan.svg'),
  israel: () => import('./flags/israel.svg'),
  italy: () => import('./flags/italy.svg'),
  ivoryCoast: () => import('./flags/ivoryCoast.svg'),
  jamaica: () => import('./flags/jamaica.svg'),
  japan: () => import('./flags/japan.svg'),
  jersey: () => import('./flags/jersey.svg'),
  jordan: () => import('./flags/jordan.svg'),
  kazakhstan: () => import('./flags/kazakhstan.svg'),
  kenya: () => import('./flags/kenya.svg'),
  kiribati: () => import('./flags/kiribati.svg'),
  kosovo: () => import('./flags/kosovo.svg'),
  kuwait: () => import('./flags/kuwait.svg'),
  kyrgyzstan: () => import('./flags/kyrgyzstan.svg'),
  laos: () => import('./flags/laos.svg'),
  latvia: () => import('./flags/latvia.svg'),
  lebanon: () => import('./flags/lebanon.svg'),
  lesotho: () => import('./flags/lesotho.svg'),
  liberia: () => import('./flags/liberia.svg'),
  libya: () => import('./flags/libya.svg'),
  liechtenstein: () => import('./flags/liechtenstein.svg'),
  lithuania: () => import('./flags/lithuania.svg'),
  luxembourg: () => import('./flags/luxembourg.svg'),
  macao: () => import('./flags/macao.svg'),
  madagascar: () => import('./flags/madagascar.svg'),
  madeira: () => import('./flags/madeira.svg'),
  malawi: () => import('./flags/malawi.svg'),
  malaysia: () => import('./flags/malaysia.svg'),
  maldives: () => import('./flags/maldives.svg'),
  mali: () => import('./flags/mali.svg'),
  malta: () => import('./flags/malta.svg'),
  marshallIsland: () => import('./flags/marshallIsland.svg'),
  martinique: () => import('./flags/martinique.svg'),
  mauritania: () => import('./flags/mauritania.svg'),
  mauritius: () => import('./flags/mauritius.svg'),
  melilla: () => import('./flags/melilla.svg'),
  mexico: () => import('./flags/mexico.svg'),
  micronesia: () => import('./flags/micronesia.svg'),
  moldova: () => import('./flags/moldova.svg'),
  monaco: () => import('./flags/monaco.svg'),
  mongolia: () => import('./flags/mongolia.svg'),
  montenegro: () => import('./flags/montenegro.svg'),
  montserrat: () => import('./flags/montserrat.svg'),
  morocco: () => import('./flags/morocco.svg'),
  mozambique: () => import('./flags/mozambique.svg'),
  myanmar: () => import('./flags/myanmar.svg'),
  namibia: () => import('./flags/namibia.svg'),
  nato: () => import('./flags/nato.svg'),
  nauru: () => import('./flags/nauru.svg'),
  nepal: () => import('./flags/nepal.svg'),
  netherlands: () => import('./flags/netherlands.svg'),
  newZealand: () => import('./flags/newZealand.svg'),
  nicaragua: () => import('./flags/nicaragua.svg'),
  niger: () => import('./flags/niger.svg'),
  nigeria: () => import('./flags/nigeria.svg'),
  niue: () => import('./flags/niue.svg'),
  norfolkIsland: () => import('./flags/norfolkIsland.svg'),
  northKorea: () => import('./flags/northKorea.svg'),
  northenCyprus: () => import('./flags/northenCyprus.svg'),
  northernMarianasIslands: () => import('./flags/northernMarianasIslands.svg'),
  norway: () => import('./flags/norway.svg'),
  oman: () => import('./flags/oman.svg'),
  orkneyIslands: () => import('./flags/orkneyIslands.svg'),
  ossetia: () => import('./flags/ossetia.svg'),
  pakistan: () => import('./flags/pakistan.svg'),
  palau: () => import('./flags/palau.svg'),
  palestine: () => import('./flags/palestine.svg'),
  panama: () => import('./flags/panama.svg'),
  papuaNewGuinea: () => import('./flags/papuaNewGuinea.svg'),
  paraguay: () => import('./flags/paraguay.svg'),
  peru: () => import('./flags/peru.svg'),
  philippines: () => import('./flags/philippines.svg'),
  pitcairnIslands: () => import('./flags/pitcairnIslands.svg'),
  portugal: () => import('./flags/portugal.svg'),
  puertoRico: () => import('./flags/puertoRico.svg'),
  qatar: () => import('./flags/qatar.svg'),
  rapaNui: () => import('./flags/rapaNui.svg'),
  republicOfMacedonia: () => import('./flags/republicOfMacedonia.svg'),
  republicOfPoland: () => import('./flags/republicOfPoland.svg'),
  republicOfTheCongo: () => import('./flags/republicOfTheCongo.svg'),
  romania: () => import('./flags/romania.svg'),
  russia: () => import('./flags/russia.svg'),
  rwanda: () => import('./flags/rwanda.svg'),
  sabaIsland: () => import('./flags/sabaIsland.svg'),
  saintKittsAndNevis: () => import('./flags/saintKittsAndNevis.svg'),
  salvador: () => import('./flags/salvador.svg'),
  samoa: () => import('./flags/samoa.svg'),
  sanMarino: () => import('./flags/sanMarino.svg'),
  saoTomeAndPrincipe: () => import('./flags/saoTomeAndPrincipe.svg'),
  sardinia: () => import('./flags/sardinia.svg'),
  saudiArabia: () => import('./flags/saudiArabia.svg'),
  scotland: () => import('./flags/scotland.svg'),
  senegal: () => import('./flags/senegal.svg'),
  serbia: () => import('./flags/serbia.svg'),
  seychelles: () => import('./flags/seychelles.svg'),
  sierraLeone: () => import('./flags/sierraLeone.svg'),
  singapore: () => import('./flags/singapore.svg'),
  sintEustatius: () => import('./flags/sintEustatius.svg'),
  sintMaarten: () => import('./flags/sintMaarten.svg'),
  slovakia: () => import('./flags/slovakia.svg'),
  slovenia: () => import('./flags/slovenia.svg'),
  solomonIslands: () => import('./flags/solomonIslands.svg'),
  somalia: () => import('./flags/somalia.svg'),
  somaliland: () => import('./flags/somaliland.svg'),
  southAfrica: () => import('./flags/southAfrica.svg'),
  southKorea: () => import('./flags/southKorea.svg'),
  southSudan: () => import('./flags/southSudan.svg'),
  spain: () => import('./flags/spain.svg'),
  sriLanka: () => import('./flags/sriLanka.svg'),
  stBarts: () => import('./flags/stBarts.svg'),
  stLucia: () => import('./flags/stLucia.svg'),
  stVincentAndTheGrenadines: () =>
    import('./flags/stVincentAndTheGrenadines.svg'),
  sudan: () => import('./flags/sudan.svg'),
  suriname: () => import('./flags/suriname.svg'),
  swaziland: () => import('./flags/swaziland.svg'),
  sweden: () => import('./flags/sweden.svg'),
  switzerland: () => import('./flags/switzerland.svg'),
  syria: () => import('./flags/syria.svg'),
  taiwan: () => import('./flags/taiwan.svg'),
  tajikistan: () => import('./flags/tajikistan.svg'),
  tanzania: () => import('./flags/tanzania.svg'),
  thailand: () => import('./flags/thailand.svg'),
  tibet: () => import('./flags/tibet.svg'),
  togo: () => import('./flags/togo.svg'),
  tokelau: () => import('./flags/tokelau.svg'),
  tonga: () => import('./flags/tonga.svg'),
  transnistria: () => import('./flags/transnistria.svg'),
  trinidadAndTobago: () => import('./flags/trinidadAndTobago.svg'),
  tunisia: () => import('./flags/tunisia.svg'),
  turkey: () => import('./flags/turkey.svg'),
  turkmenistan: () => import('./flags/turkmenistan.svg'),
  turksAndCaicos: () => import('./flags/turksAndCaicos.svg'),
  tuvalu: () => import('./flags/tuvalu.svg'),
  uganda: () => import('./flags/uganda.svg'),
  ukraine: () => import('./flags/ukraine.svg'),
  unitedArabEmirates: () => import('./flags/unitedArabEmirates.svg'),
  unitedKingdom: () => import('./flags/unitedKingdom.svg'),
  unitedNations: () => import('./flags/unitedNations.svg'),
  unitedStatesOfAmerica: () => import('./flags/unitedStatesOfAmerica.svg'),
  uruguay: () => import('./flags/uruguay.svg'),
  uzbekistn: () => import('./flags/uzbekistn.svg'),
  vanuatu: () => import('./flags/vanuatu.svg'),
  vaticanCity: () => import('./flags/vaticanCity.svg'),
  venezuela: () => import('./flags/venezuela.svg'),
  vietnam: () => import('./flags/vietnam.svg'),
  virginIslands: () => import('./flags/virginIslands.svg'),
  wales: () => import('./flags/wales.svg'),
  westernSahara: () => import('./flags/westernSahara.svg'),
  yemen: () => import('./flags/yemen.svg'),
  zambia: () => import('./flags/zambia.svg'),
  zimbabwe: () => import('./flags/zimbabwe.svg'),
};

// Cache for loaded flag components — avoids flicker on re-render
const flagCache = new Map<IconCountryFlagVariant, SvgComponent>();

/** Synchronous cache lookup — returns null if not yet loaded */
export function getCachedFlag(
  name: IconCountryFlagVariant
): SvgComponent | null {
  return flagCache.get(name) ?? null;
}

export async function getFlag(
  name: IconCountryFlagVariant
): Promise<SvgComponent | null> {
  const cached = flagCache.get(name);
  if (cached) return cached;

  const loader = flagLoaders[name];
  if (!loader) return null;

  const mod = await loader();
  const component = mod.default;
  flagCache.set(name, component);
  return component;
}
